version: "3.8"
services:

  db:
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_DB: amigoscode
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test1234.
    ports:
      - 5432:5432
    volumes: 
        - postgres-volume:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
volumes:
    postgres-volume: